spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/study-manager
        username: bootuser
        password: bootuser

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true

    mail:
        host: smtp.gmail.com
        port: 587
        username: jihorak94@gmail.com
        password: jsjiuojjgskkoeub
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true

server:
    tomcat:
        max-http-form-post-size: 5MB

logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE

app:
    host: http://jihorak.space